name: Test AnonSurf Installation and Functionality on kali-rolling

on:
  pull_request: # Trigger on all pull requests
    branches:
      - '**' # All branches for pull requests
  push: # Trigger on pushes to specific branches
    branches:
      - master # Only on merges to master

jobs:
  test-script:
    runs-on: ubuntu-latest
    container:
      image: kalilinux/kali-rolling:latest  # Use a Kali Linux environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y dpkg-dev curl bleachbit tor iptables secure-delete

   - name: Run Installer Script
      run: |
        chmod +x installer.sh
        ./installer.sh

    - name: Verify Installation
      run: |
        which anonsurf || { echo "ERROR: anonsurf is not installed."; exit 1; }

    - name: Test AnonSurf Functionality
      run: |
        echo "Starting AnonSurf..."
        anonsurf start

        echo "Testing if IPv6 is disabled..."
        if [ "$(sysctl net.ipv6.conf.all.disable_ipv6 | awk '{print $3}')" != "1" ]; then
          echo "ERROR: IPv6 is not disabled!"
          anonsurf stop
          exit 1
        fi
        echo "IPv6 is successfully disabled."

        echo "Stopping AnonSurf and restoring network configuration..."
        anonsurf stop
